baseURL = 'https://pehtheme-hugo.netlify.app/'
languageCode = 'en-us'
title = 'Pehtheme'
theme = 'pehtheme-hugo'
publishDir = "public"


paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com
