baseURL = "https://cuteloop.github.io/vdancehub-blog/"  # <— trailing slash
relativeURLs = true
canonifyURLs = true

languageCode = "en-us"
title = "Sparks of Connection"
theme = "pehtheme-hugo"
publishDir = "public"

summaryLength = 20
googleAnalytics = ""
disqusShortname = ""

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Cumbia, salsa, bachata — notes from the floor."
  mainSections = ["posts"]
  brand = "Sparks of Connection"

  [params.home]
    featureTag = "feature"      # any post with this tag becomes the hero
    category  = "dance"         # section block title + filter (set "" to hide)

  [params.social]
    facebook  = "https://www.facebook.com/sparksofconnection"
    instagram = "https://www.instagram.com/sparksofconnection/"

[author]
  name = "Joel"
  bio = "Applied math by day, dancer by night."
  avatar = "/images/nasa-astronaut-unsplash.jpg"
  twitter = "https://twitter.com/insertapps"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    pageRef = "about"           # matches content/about.md or content/about/_index.md
    weight = 15

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 25

[module]
  [module.hugoVersion]
    extended = true
    min = "0.148.0"

  [[module.mounts]]
    source = "assets"
    target = "static"
